/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amigo_ndk_target_one_NdkUtils */

#ifndef _Included_com_amigo_ndk_target_one_NdkUtils
#define _Included_com_amigo_ndk_target_one_NdkUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_amigo_ndk_target_one_NdkUtils
 * Method:    dothing
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_amigo_ndk_target_one_NdkUtils_dothing
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
