/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ndk_test_two_NdkUtils */

#ifndef _Included_com_ndk_test_two_NdkUtils
#define _Included_com_ndk_test_two_NdkUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ndk_test_two_NdkUtils
 * Method:    getResult
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ndk_test_two_NdkUtils_getResult
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
