package com.mx.http.download;

public enum i {
    UNKNOW,
    HOPE_INSTALL,
    HOPE_UPDATE,
    DOWNLOAD_COMPLETE,
    WAIT_INSTALL,
    WAIT_UPDATE,
    INSTALLED,
    DOWNLOAD_FAILED,
    DOWNLOAD_PAUSE,
    DOWNLOAD_PENDING,
    DOWNLOAD_CANCEL,
    DOWNLOAD_NETWORK_UNAVAILABLE,
    DOWNLOADING,
    INSTALL_FAIL
}
